"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, CalendarDays, CheckCircle2, Circle, CircleDollarSign, ClipboardList, FileText, FolderKanban, LoaderCircle, Plus, ReceiptText, Sparkles, TrendingDown, TrendingUp, WalletCards } from "lucide-react";

import { DashboardNav } from "@/components/dashboard/dashboard-nav";
import { FinancialContextSwitcher } from "@/components/financial/financial-context-switcher";
import { OnboardingChecklist } from "@/components/dashboard/onboarding-checklist";

type Transaction = { id: string; description: string; category: string; type: "INCOME" | "EXPENSE"; amount: number; date: string; user?: { name: string | null; email: string | null } };
type Workspace = { key: string; label: string; type: "PERSONAL" | "FAMILY"; role?: string };
type AgendaEvent = { id: string; title: string; startTime: string };
type Summary = {
  user: { name: string | null };
  month: { income: number; expense: number; balance: number; transactionCount: number };
  recentTransactions: Transaction[];
  upcomingEvents: AgendaEvent[];
  expenseCategories: { category: string; amount: number }[];
  activeProjects: { id: string; name: string; description: string | null; doneTasks: number; totalTasks: number }[];
  pendingTasks: { id: string; title: string; priority: string; status: string; project: { name: string } }[];
  notesCount: number;
  setup: { transactionCount: number; eventCount: number; importedTransactionCount: number };
  upcomingStatement: { cardName: string; amount: number; dueDate: string } | null;
  context: { key: string; name: string; type: "PERSONAL" | "FAMILY" };
};

const currency = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const dateFormatter = new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short" });
const timeFormatter = new Intl.DateTimeFormat("pt-BR", { hour: "2-digit", minute: "2-digit" });
const monthFormatter = new Intl.DateTimeFormat("pt-BR", { month: "long", year: "numeric" });

export function DashboardOverview() {
  const [summary, setSummary] = useState<Summary | null>(null);
  const [workspaces, setWorkspaces] = useState<Workspace[]>([]);
  const [context, setContext] = useState("personal");
  const [error, setError] = useState("");

  const loadSummary = useCallback(async () => {
    try {
      const response = await fetch(`/api/dashboard/summary?context=${encodeURIComponent(context)}`);
      const body = (await response.json()) as Summary & { error?: string };
      if (!response.ok) throw new Error(body.error || "Não foi possível carregar seu painel.");
      setSummary(body);
    } catch (requestError) {
      setError(requestError instanceof Error ? requestError.message : "Não foi possível carregar seu painel.");
    }
  }, [context]);

  useEffect(() => { void loadSummary(); }, [loadSummary]);
  useEffect(() => { void fetch("/api/financial/workspaces").then((response) => response.json()).then((data: { workspaces?: Workspace[] }) => setWorkspaces(data.workspaces || [])).catch(() => undefined); }, []);

  const firstName = summary?.user.name?.split(" ")[0] || "";
  const expensePercentage = useMemo(() => summary?.month.income ? Math.min(100, Math.round((summary.month.expense / summary.month.income) * 100)) : 0, [summary]);
  const largestCategory = summary?.expenseCategories[0];

  return <div className="min-h-[100dvh] bg-[#f4f8f5] text-[#17372b]"><DashboardNav activePath="/dashboard" /><main className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-10 lg:py-10"><header className="relative overflow-hidden rounded-[2rem] bg-[#123d2b] px-6 py-7 text-white shadow-[0_28px_70px_-42px_rgba(12,73,43,0.7)] sm:px-9 sm:py-9"><div className="absolute -right-20 -top-28 h-72 w-72 rounded-full bg-[#31bc6c]/25 blur-3xl" /><div className="absolute bottom-0 left-[38%] h-40 w-40 rounded-full bg-[#d7ff8f]/10 blur-3xl" /><div className="relative flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#9be7b6]">{summary?.context.type === "FAMILY" ? `${summary.context.name} · visão familiar` : `Visão geral · ${monthFormatter.format(new Date())}`}</p><h1 className="mt-3 max-w-2xl text-3xl font-semibold tracking-[-0.055em] sm:text-5xl">{firstName ? `Bom ter você, ${firstName}.` : "Seu dia começa bem aqui."}</h1><p className="mt-3 max-w-xl text-sm leading-relaxed text-[#c4decf] sm:text-base">Seu dinheiro, compromissos e prioridades numa leitura que ajuda a decidir o próximo passo.</p></div><div className="flex flex-wrap gap-3"><div className="rounded-xl bg-white p-1 text-[#17372b]"><FinancialContextSwitcher workspaces={workspaces} value={context} onChange={setContext} /></div><Link href="/dashboard/agenda" className="inline-flex h-11 items-center gap-2 rounded-xl border border-white/20 bg-white/10 px-4 text-sm font-semibold backdrop-blur transition hover:bg-white/18"><CalendarDays className="h-4 w-4" /> Novo compromisso</Link><Link href={`/dashboard/financeiro/transacoes${context === "personal" ? "" : `?context=${encodeURIComponent(context)}`}`} className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#d8ff8e] px-4 text-sm font-bold text-[#174429] shadow-[0_12px_24px_-14px_rgba(0,0,0,0.55)] transition hover:-translate-y-0.5 hover:bg-[#e5ffad]"><Plus className="h-4 w-4" /> Nova transação</Link></div></div></header>

    {error ? <p className="mt-6 rounded-2xl bg-[#fff1f1] px-5 py-4 text-sm text-[#a93636]">{error}</p> : !summary ? <DashboardSkeleton /> : <><OnboardingChecklist setup={summary.setup} /><section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Saldo disponível" value={currency.format(summary.month.balance)} icon={<CircleDollarSign className="h-5 w-5" />} tone="green" hint={summary.month.balance >= 0 ? "Resultado do mês até agora" : "Atenção ao ritmo de gastos"} /><Metric label="Entradas" value={currency.format(summary.month.income)} icon={<TrendingUp className="h-5 w-5" />} tone="lime" hint="Recebido neste mês" /><Metric label="Saídas" value={currency.format(summary.month.expense)} icon={<TrendingDown className="h-5 w-5" />} tone="coral" hint={largestCategory ? `${largestCategory.category} lidera os gastos` : "Nenhuma saída registrada"} /><Metric label="Lançamentos" value={String(summary.month.transactionCount).padStart(2, "0")} icon={<ReceiptText className="h-5 w-5" />} tone="ink" hint="Movimentações registradas" /></section>

      <section className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.45fr)_minmax(18rem,0.75fr)]"><article className="relative overflow-hidden rounded-[2rem] bg-white p-6 shadow-[0_26px_70px_-48px_rgba(12,100,53,0.4)] sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#079347]">Pulso financeiro</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.045em]">O retrato do seu mês.</h2></div><Link href="/dashboard/financeiro/transacoes" className="text-sm font-bold text-[#087d3c] transition hover:text-[#055f30]">Abrir financeiro →</Link></div><div className="mt-7 grid gap-5 md:grid-cols-[minmax(0,1fr)_13rem]"><div className="rounded-2xl bg-[#f2f8f4] p-5"><div className="flex items-end justify-between"><div><p className="text-sm font-medium text-[#698477]">Você já registrou</p><p className="mt-1 text-3xl font-semibold tracking-[-0.055em] tabular-nums">{currency.format(summary.month.expense)}</p></div><span className="rounded-xl bg-white px-3 py-2 text-sm font-bold text-[#087d3c]">{expensePercentage}%</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-[#dcebe2]"><div className="h-full rounded-full bg-[#0b9d4e] transition-all duration-500" style={{ width: `${expensePercentage}%` }} /></div><p className="mt-3 text-xs leading-relaxed text-[#789083]">{summary.month.income ? "das suas entradas registradas neste mês foram usadas." : "Registre entradas e saídas para acompanhar seu ritmo financeiro."}</p></div><div className="rounded-2xl border border-[#e2eee6] p-5"><p className="text-sm font-semibold text-[#315f48]">Maior categoria</p>{largestCategory ? <><p className="mt-3 text-xl font-semibold tracking-[-0.04em]">{largestCategory.category}</p><p className="mt-1 text-sm font-medium text-[#b35445]">{currency.format(largestCategory.amount)}</p></> : <p className="mt-3 text-sm leading-relaxed text-[#789083]">Seu primeiro gasto aparecerá aqui.</p>}</div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><MiniStat label="Entradas" value={currency.format(summary.month.income)} tone="text-[#087d3c]" /><MiniStat label="Saídas" value={currency.format(summary.month.expense)} tone="text-[#b35445]" /><MiniStat label="Saldo" value={currency.format(summary.month.balance)} tone="text-[#17372b]" /></div></article>
        <AgendaPanel events={summary.upcomingEvents} /></section>

      <section className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)]"><article className="rounded-[2rem] bg-white p-6 shadow-[0_26px_70px_-48px_rgba(12,100,53,0.4)] sm:p-7"><PanelHeading kicker="Movimentações" title="Últimos lançamentos" href={`/dashboard/financeiro/transacoes${context === "personal" ? "" : `?context=${encodeURIComponent(context)}`}`} action="Ver tudo" />{summary.recentTransactions.length ? <div className="mt-5 divide-y divide-[#edf3ef]">{summary.recentTransactions.map((transaction) => <div key={transaction.id} className="flex items-center justify-between gap-4 py-3.5 first:pt-0"><div className="flex min-w-0 items-center gap-3"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${transaction.type === "INCOME" ? "bg-[#e5f7eb] text-[#087d3c]" : "bg-[#fff0ed] text-[#b35445]"}`}>{transaction.type === "INCOME" ? <ArrowUpRight className="h-4 w-4" /> : <ArrowDownRight className="h-4 w-4" />}</span><div className="min-w-0"><p className="truncate text-sm font-bold">{transaction.description}</p><p className="mt-0.5 text-xs text-[#789083]">{transaction.category} · {dateFormatter.format(new Date(transaction.date))}{summary.context.type === "FAMILY" && transaction.user ? ` · ${transaction.user.name || transaction.user.email || "Membro"}` : ""}</p></div></div><p className={`shrink-0 text-sm font-bold tabular-nums ${transaction.type === "INCOME" ? "text-[#087d3c]" : "text-[#b35445]"}`}>{transaction.type === "INCOME" ? "+" : "−"}{currency.format(transaction.amount)}</p></div>)}</div> : <InlineEmpty icon={<WalletCards className="h-5 w-5" />} text="Registre a primeira movimentação para destravar seu resumo financeiro." href="/dashboard/financeiro/transacoes" action="Registrar" />}</article>
        <ProjectsPanel projects={summary.activeProjects} notesCount={summary.notesCount} /></section>

      <section className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)]"><article className="rounded-[2rem] bg-white p-6 shadow-[0_26px_70px_-48px_rgba(12,100,53,0.4)] sm:p-7"><PanelHeading kicker="Foco de hoje" title="Pendências para avançar" href="/dashboard/organizacao/tarefas" action="Abrir tarefas" />{summary.pendingTasks.length ? <div className="mt-5 space-y-3">{summary.pendingTasks.map((task) => <Link key={task.id} href="/dashboard/organizacao/tarefas" className="flex items-center gap-3 rounded-2xl bg-[#f4f8f5] px-4 py-3 transition hover:bg-[#eaf5ed]"><Circle className="h-5 w-5 shrink-0 text-[#5e9c76]" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{task.title}</p><p className="mt-0.5 text-xs text-[#789083]">{task.project.name}</p></div><span className={`text-xs font-bold ${task.priority === "HIGH" ? "text-[#b35445]" : "text-[#688176]"}`}>{task.priority === "HIGH" ? "Prioridade alta" : "Pendente"}</span></Link>)}</div> : <InlineEmpty icon={<ClipboardList className="h-5 w-5" />} text="Nenhuma pendência por enquanto. Crie uma tarefa para manter o ritmo." href="/dashboard/organizacao/projetos" action="Criar tarefa" />}</article>
        <article className="relative overflow-hidden rounded-[2rem] bg-[#e8f7ec] p-6 sm:p-7"><div className="absolute -right-8 -top-8 h-32 w-32 rounded-full bg-[#c9ef9b]/70 blur-2xl" /><div className="relative"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-white text-[#087d3c] shadow-sm"><Sparkles className="h-5 w-5" /></div><p className="mt-6 text-xs font-bold uppercase tracking-[0.15em] text-[#258252]">{summary.upcomingStatement ? "Próximo compromisso" : "Atalhos úteis"}</p>{summary.upcomingStatement ? <><h2 className="mt-2 text-2xl font-semibold tracking-[-0.045em]">Fatura {summary.upcomingStatement.cardName}</h2><p className="mt-3 max-w-sm text-sm leading-relaxed text-[#537766]">{currency.format(summary.upcomingStatement.amount)} com vencimento em {new Date(summary.upcomingStatement.dueDate).toLocaleDateString("pt-BR")}.</p><Link href="/dashboard/financeiro/cartoes" className="mt-6 inline-flex rounded-xl bg-[#087d3c] px-4 py-3 text-sm font-bold text-white transition hover:bg-[#056c35]">Abrir cartões →</Link></> : <><h2 className="mt-2 text-2xl font-semibold tracking-[-0.045em]">Deixe o painel trabalhar para você.</h2><p className="mt-3 max-w-sm text-sm leading-relaxed text-[#537766]">Acesse o que mais importa agora, sem passar por menus.</p><div className="mt-6 grid gap-2 sm:grid-cols-2"><QuickLink href="/dashboard/agenda" icon={<CalendarDays className="h-4 w-4" />} label="Planejar agenda" /><QuickLink href="/dashboard/organizacao/notas" icon={<FileText className="h-4 w-4" />} label="Nova anotação" /><QuickLink href="/dashboard/organizacao/projetos" icon={<FolderKanban className="h-4 w-4" />} label="Ver projetos" /><QuickLink href="/dashboard/financeiro/transacoes" icon={<CircleDollarSign className="h-4 w-4" />} label="Registrar gasto" /></div></>}</div></article></section></>}</main></div>;
}

function Metric({ label, value, icon, tone, hint }: { label: string; value: string; icon: React.ReactNode; tone: "green" | "lime" | "coral" | "ink"; hint: string }) {
  const styles = { green: "bg-[#e5f7eb] text-[#087d3c]", lime: "bg-[#f1f9d8] text-[#5d7b20]", coral: "bg-[#fff0ed] text-[#b35445]", ink: "bg-[#eaf0ed] text-[#315f48]" };
  return <article className="rounded-[1.6rem] bg-white p-5 shadow-[0_18px_40px_-32px_rgba(12,100,53,0.32)]"><div className={`grid h-10 w-10 place-items-center rounded-xl ${styles[tone]}`}>{icon}</div><p className="mt-5 text-sm font-medium text-[#718b7e]">{label}</p><p className="mt-1 text-2xl font-semibold tracking-[-0.05em] tabular-nums">{value}</p><p className="mt-2 truncate text-xs text-[#8ba096]">{hint}</p></article>;
}

function AgendaPanel({ events }: { events: AgendaEvent[] }) { return <article className="rounded-[2rem] bg-[#173e2d] p-6 text-white shadow-[0_26px_70px_-48px_rgba(12,73,43,0.68)] sm:p-7"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#9be7b6]">Próximos 7 dias</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.045em]">Sua agenda</h2></div><Link href="/dashboard/agenda" className="rounded-xl bg-white/10 px-3 py-2 text-sm font-bold text-[#ddf7e7] transition hover:bg-white/20">Abrir</Link></div>{events.length ? <div className="mt-7 space-y-3">{events.map((event) => <div key={event.id} className="rounded-2xl border border-white/10 bg-white/8 p-4"><p className="text-sm font-bold">{event.title}</p><p className="mt-1 text-xs text-[#bcd8c8]">{dateFormatter.format(new Date(event.startTime))} · {timeFormatter.format(new Date(event.startTime))}</p></div>)}</div> : <div className="mt-8 rounded-2xl border border-dashed border-white/20 px-5 py-8 text-center"><CalendarDays className="mx-auto h-6 w-6 text-[#9be7b6]" /><p className="mt-3 text-sm font-bold">Nenhum compromisso marcado</p><p className="mt-2 text-xs leading-relaxed text-[#bcd8c8]">Reserve um horário para o que não pode ficar de fora.</p><Link href="/dashboard/agenda" className="mt-5 inline-block text-sm font-bold text-[#d8ff8e]">Planejar semana →</Link></div>}</article>; }

function ProjectsPanel({ projects, notesCount }: { projects: Summary["activeProjects"]; notesCount: number }) { return <article className="rounded-[2rem] bg-white p-6 shadow-[0_26px_70px_-48px_rgba(12,100,53,0.4)] sm:p-7"><PanelHeading kicker="Organização" title="Projetos em movimento" href="/dashboard/organizacao/projetos" action="Ver projetos" />{projects.length ? <div className="mt-5 space-y-4">{projects.map((project) => { const progress = project.totalTasks ? Math.round((project.doneTasks / project.totalTasks) * 100) : 0; return <Link key={project.id} href="/dashboard/organizacao/projetos" className="block rounded-2xl bg-[#f4f8f5] p-4 transition hover:bg-[#eaf5ed]"><div className="flex justify-between gap-3"><p className="truncate text-sm font-bold">{project.name}</p><span className="text-xs font-bold text-[#087d3c]">{progress}%</span></div><p className="mt-1 truncate text-xs text-[#789083]">{project.totalTasks ? `${project.doneTasks} de ${project.totalTasks} tarefas concluídas` : "Pronto para receber tarefas"}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#dcebe2]"><div className="h-full rounded-full bg-[#0b9d4e]" style={{ width: `${progress}%` }} /></div></Link>; })}</div> : <InlineEmpty icon={<FolderKanban className="h-5 w-5" />} text="Agrupe suas próximas entregas em projetos." href="/dashboard/organizacao/projetos" action="Criar projeto" />}<Link href="/dashboard/organizacao/notas" className="mt-5 flex items-center justify-between rounded-2xl border border-[#e3eee7] px-4 py-3 text-sm transition hover:bg-[#f6faf7]"><span className="flex items-center gap-2 font-semibold"><FileText className="h-4 w-4 text-[#087d3c]" /> Notas salvas</span><span className="font-bold text-[#087d3c]">{notesCount}</span></Link></article>; }

function PanelHeading({ kicker, title, href, action }: { kicker: string; title: string; href: string; action: string }) { return <div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#079347]">{kicker}</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.045em]">{title}</h2></div><Link href={href} className="mt-1 shrink-0 text-sm font-bold text-[#087d3c] transition hover:text-[#055f30]">{action} →</Link></div>; }

function MiniStat({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className="rounded-xl border border-[#e3eee7] px-4 py-3"><p className="text-xs font-semibold text-[#789083]">{label}</p><p className={`mt-1 text-sm font-bold tabular-nums ${tone}`}>{value}</p></div>; }

function InlineEmpty({ icon, text, href, action }: { icon: React.ReactNode; text: string; href: string; action: string }) { return <div className="mt-7 rounded-2xl bg-[#f4f8f5] px-5 py-7 text-center"><span className="mx-auto grid h-10 w-10 place-items-center rounded-xl bg-white text-[#087d3c]">{icon}</span><p className="mx-auto mt-3 max-w-sm text-sm leading-relaxed text-[#698477]">{text}</p><Link href={href} className="mt-3 inline-block text-sm font-bold text-[#087d3c]">{action} →</Link></div>; }

function QuickLink({ href, icon, label }: { href: string; icon: React.ReactNode; label: string }) { return <Link href={href} className="flex items-center gap-2 rounded-xl bg-white/75 px-3 py-3 text-sm font-bold text-[#315f48] shadow-sm transition hover:-translate-y-0.5 hover:bg-white"><span className="text-[#087d3c]">{icon}</span>{label}</Link>; }

function DashboardSkeleton() { return <div className="mt-6 animate-pulse space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <div key={index} className="h-40 rounded-[1.6rem] bg-white" />)}</div><div className="grid gap-6 xl:grid-cols-[1.45fr_0.75fr]"><div className="h-80 rounded-[2rem] bg-white" /><div className="h-80 rounded-[2rem] bg-[#173e2d]/20" /></div><div className="grid gap-6 xl:grid-cols-2"><div className="h-72 rounded-[2rem] bg-white" /><div className="h-72 rounded-[2rem] bg-white" /></div></div>; }
